// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_registro_livros.Data;

namespace backend_registro_livros.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20241124020315_AjustarChavesEstrangeiras")]
    partial class AjustarChavesEstrangeiras
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("backend_registro_livros.Models.Assunto", b =>
                {
                    b.Property<int>("CodAs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.HasKey("CodAs");

                    b.ToTable("Assunto");
                });

            modelBuilder.Entity("backend_registro_livros.Models.Autor", b =>
                {
                    b.Property<int>("CodAu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("CodAu");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("backend_registro_livros.Models.Livro", b =>
                {
                    b.Property<int>("Codl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnoPublicacao")
                        .HasColumnType("longtext");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<string>("Editora")
                        .HasColumnType("longtext");

                    b.Property<string>("FormaCompra")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("Codl");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("backend_registro_livros.Models.LivroAssunto", b =>
                {
                    b.Property<int>("Livro_Codl")
                        .HasColumnType("int");

                    b.Property<int>("Assunto_CodAs")
                        .HasColumnType("int");

                    b.Property<int?>("AssuntoCodAs")
                        .HasColumnType("int");

                    b.Property<int?>("LivroCodl")
                        .HasColumnType("int");

                    b.HasKey("Livro_Codl", "Assunto_CodAs");

                    b.HasIndex("AssuntoCodAs");

                    b.HasIndex("LivroCodl");

                    b.ToTable("Livro_Assunto");
                });

            modelBuilder.Entity("backend_registro_livros.Models.LivroAutor", b =>
                {
                    b.Property<int>("Livro_Codl")
                        .HasColumnType("int");

                    b.Property<int>("Autor_CodAu")
                        .HasColumnType("int");

                    b.HasKey("Livro_Codl", "Autor_CodAu");

                    b.HasIndex("Autor_CodAu");

                    b.ToTable("Livro_Autor");
                });

            modelBuilder.Entity("backend_registro_livros.Models.LivroAssunto", b =>
                {
                    b.HasOne("backend_registro_livros.Models.Assunto", "Assunto")
                        .WithMany("LivrosAssuntos")
                        .HasForeignKey("AssuntoCodAs");

                    b.HasOne("backend_registro_livros.Models.Livro", "Livro")
                        .WithMany("LivrosAssuntos")
                        .HasForeignKey("LivroCodl");

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("backend_registro_livros.Models.LivroAutor", b =>
                {
                    b.HasOne("backend_registro_livros.Models.Autor", "Autor")
                        .WithMany("LivrosAutores")
                        .HasForeignKey("Autor_CodAu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend_registro_livros.Models.Livro", "Livro")
                        .WithMany("LivrosAutores")
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("backend_registro_livros.Models.Assunto", b =>
                {
                    b.Navigation("LivrosAssuntos");
                });

            modelBuilder.Entity("backend_registro_livros.Models.Autor", b =>
                {
                    b.Navigation("LivrosAutores");
                });

            modelBuilder.Entity("backend_registro_livros.Models.Livro", b =>
                {
                    b.Navigation("LivrosAssuntos");

                    b.Navigation("LivrosAutores");
                });
#pragma warning restore 612, 618
        }
    }
}
